name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc python3-dev
          pip install -r requirements.txt
      - name: Build extension
        run: make build
      - name: Run tests
        run: make test

  security-scan:
    runs-on: ubuntu-latest
    name: Security Scan

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety

      - name: Run Bandit security scan
        run: |
          # Create __init__.py if it doesn't exist
          touch python_interface/__init__.py
          bandit -r python_interface/ -f json -o bandit-report.json || echo "Bandit scan completed with issues"

      - name: Check for known vulnerabilities
        run: |
          pip install -r requirements.txt
          safety check || echo "Safety check completed"

  deploy:
    runs-on: ubuntu-latest
    needs: [build-test, security-scan]
    name: Deploy Package
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          pip install -r requirements.txt

      - name: Create missing __init__.py
        run: |
          python -c "
          import os
          os.makedirs('python_interface', exist_ok=True)
          with open('python_interface/__init__.py', 'w') as f:
              f.write('from ._calc import add, sub, mul, divide\n')
          "

      - name: Build package
        run: |
          python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-packages
          path: dist/
