name: CI/CD Pipeline

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    name: Code Quality Check

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort pylint
          pip install -r requirements.txt

      - name: Run code formatting checks
        run: |
          black --check python_interface/ || echo "Black formatting issues found"
          isort --check-only python_interface/ || echo "Import sorting issues found"

      - name: Run linting
        run: |
          flake8 python_interface/ --max-line-length=88 --ignore=E203,W503 --exclude=__pycache__
          pylint python_interface/ --disable=C0111,C0103,R0903 --ignore=__pycache__ || true

  security-scan:
    runs-on: ubuntu-latest
    name: Security Scan

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety

      - name: Run Bandit security scan
        run: |
          bandit -r python_interface/ -f json -o bandit-report.json || true
          bandit -r python_interface/ || echo "Security issues found but continuing"

      - name: Check for known vulnerabilities
        run: |
          pip install -r requirements.txt
          safety check || echo "Vulnerability check completed"

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
        exclude:
          # Reduce matrix size for efficiency
          - os: windows-latest
            python-version: "3.9"
          - os: macos-latest
            python-version: "3.9"

    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install system dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          # Xcode command line tools should be available
          xcode-select --install || true

      - name: Setup MSVC (Windows)
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.3

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -r requirements.txt

      - name: Build C extension
        run: |
          python setup.py build_ext --inplace

      - name: Test C backend
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            # Windows compilation
            cl tests/test_c_calc.c c_backend/calc.c /Fe:tests/test_c_calc.exe /I c_backend
            ./tests/test_c_calc.exe
            rm -f tests/test_c_calc.exe tests/*.obj
          else
            # Unix-like systems
            gcc -std=c99 -Wall -Wextra -I c_backend -o tests/test_c_calc tests/test_c_calc.c c_backend/calc.c
            ./tests/test_c_calc
            rm -f tests/test_c_calc
          fi

      - name: Test Python interface
        run: |
          python -m pytest python_interface/test_python_calc.py -v --tb=short

      - name: Install package
        run: |
          pip install -e .

      - name: Test CLI functionality
        shell: bash
        run: |
          calc 5 3 add | grep "5.0 + 3.0 = 8.0"
          calc 10 2 div | grep "10.0 / 2.0 = 5.0"
          calc 7 4 sub | grep "7.0 - 4.0 = 3.0"
          calc 3 6 mul | grep "3.0 \* 6.0 = 18.0"

      - name: Test division by zero
        shell: bash
        run: |
          calc 5 0 div | grep "5.0 / 0.0 = 0.0"

      - name: Run coverage tests
        if: matrix.python-version == '3.11' && matrix.os == 'ubuntu-latest'
        run: |
          pip install pytest-cov
          python -m pytest python_interface/test_python_calc.py --cov=python_interface --cov-report=xml --cov-report=html

      - name: Upload coverage reports
        if: matrix.python-version == '3.11' && matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: |
            coverage.xml
            htmlcov/

  integration-test:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    name: Integration Tests

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and install
        run: |
          python setup.py build_ext --inplace
          pip install -e .

      - name: Comprehensive integration test
        run: |
          # Test various edge cases
          python -c "
          from calculator import add, sub, mul, divide
          import sys

          # Test basic operations
          assert add(1, 1) == 2, 'Basic addition failed'
          assert sub(5, 3) == 2, 'Basic subtraction failed'
          assert mul(3, 4) == 12, 'Basic multiplication failed'
          assert divide(8, 2) == 4, 'Basic division failed'

          # Test edge cases
          assert divide(5, 0) == 0, 'Division by zero should return 0'
          assert add(-1, 1) == 0, 'Negative numbers failed'
          assert mul(0, 100) == 0, 'Multiplication by zero failed'

          # Test floating point
          assert abs(add(0.1, 0.2) - 0.3) < 1e-10, 'Floating point addition failed'
          assert abs(divide(1, 3) - 0.3333333333333333) < 1e-10, 'Floating point division failed'

          print('All integration tests passed!')
          "

  build-docs:
    runs-on: ubuntu-latest
    needs: [code-quality, build-and-test]
    name: Build Documentation

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Generate documentation
        run: |
          python -c "
          print('# CLI Calculator Documentation')
          print()
          print('## Installation')
          print('```bash')
          print('pip install -e .')
          print('```')
          print()
          print('## Usage')
          print('```bash')
          print('calc <num1> <num2> <operation>')
          print('```')
          print()
          print('## Examples')
          print('- calc 5 3 add     # 5 + 3 = 8')
          print('- calc 10 2 div    # 10 / 2 = 5')
          print('- calc 7 4 sub     # 7 - 4 = 3')
          print('- calc 3 6 mul     # 3 * 6 = 18')
          " > README.md

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: README.md

  deploy:
    runs-on: ubuntu-latest
    needs: [code-quality, security-scan, build-and-test, integration-test]
    name: Deploy Package
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          pip install -r requirements.txt

      - name: Build package
        run: |
          python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-packages
          path: dist/

    # Uncomment and configure for actual PyPI deployment
    # - name: Publish to PyPI
    #   if: success()
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     password: ${{ secrets.PYPI_API_TOKEN }}
