name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc python3-dev
          pip install -r requirements.txt
      - name: Build extension
        run: make build
      - name: Run tests
        run: make test

  security-scan:
    runs-on: ubuntu-latest
    name: Security Scan

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety

      - name: Run Bandit security scan
        run: |
          # Create __init__.py if it doesn't exist
          touch python_interface/__init__.py
          bandit -r python_interface/ -f json -o bandit-report.json || echo "Bandit scan completed with issues"

      - name: Check for known vulnerabilities
        run: |
          pip install -r requirements.txt
          safety check || echo "Safety check completed"
